### ISSUE TITLE
Don't work with react editor

### ISSUE THREAD

**Issue by MoOx** [madebysource/atom-color-highlighting#6]
If you enable react editor under settings, your plugin become unusable (everything is seen as if it were white).

![](http://cl.ly/image/3u0X1b2X1134/Screen%20Shot%202014-07-04%20at%2017.56.46.png)

**Comment by petrbrzek** [comment]
Thanks for reporting. I'll fix it.

**Comment by petrbrzek** [comment]
Hi, I don't have time for maintaining this project. Use https://github.com/abe33/atom-color-highlight instead. It works perfect.
